// Piadas curtas de computação mostradas durante a geração das perguntas, que
// depende de uma chamada de IA e pode levar dezenas de segundos.
// Manter cada linha com no máximo ~110 caracteres: acima disso o texto passa de
// três linhas no mobile e o container do loader começa a pular.
export const COMPUTING_JOKES: readonly string[] = [
  "Existem 10 tipos de pessoas: as que entendem binário e as que não.",
  "Eu ia fazer uma piada sobre recursão, mas primeiro eu ia fazer uma piada sobre recursão.",
  "Um SQL entra no bar, vai até duas mesas e pergunta: posso fazer JOIN?",
  "Cache é fácil. Invalidar cache é que separa os homens dos meninos.",
  "“Funciona na minha máquina” — últimas palavras antes do deploy de sexta.",
  "99 bugs no código. Corrige um. 127 bugs no código.",
  "Nunca é DNS. É sempre DNS.",
  "Off-by-one: o erro que acontece 0 ou 2 vezes.",
  "Meu código não tem bug, tem comportamento indocumentado.",
  "git commit -m “ajustes”: a história completa da humanidade.",
  "Regex é a solução. Agora você tem dois problemas.",
  "Programar é 10% escrever código e 90% descobrir por que não compila.",
  "O melhor lugar pra esconder um segredo é no meio de um YAML de 800 linhas.",
  "Perguntei ao júnior o que era Big O. Ele disse: o susto na fatura da AWS.",
  "Apaguei node_modules e ganhei 12 GB e uma tarde livre.",
  "“Passa localmente” é só um boato muito bem organizado.",
  "Um ponteiro nulo entra no bar. Segmentation fault.",
  "JavaScript: onde [] + {} faz sentido pra alguém, em algum lugar.",
  "NaN é um número. Confia.",
  "Rebase é como cirurgia: melhor não fazer com sono.",
  "Chamei a variável de “temp”. Ela está em produção há quatro anos.",
  "Refatorei tudo e agora ninguém entende o código, inclusive eu.",
  "Race condition só aparece quando alguém importante está olhando.",
  "Se compilou de primeira, desconfie.",
  "Documentação é uma carta de amor pro seu eu do futuro. Eu nunca escrevo cartas.",
  "Estimativa: dois dias. Realidade: dois dias — mas de qual mês?",
  "Não é lentidão, é uma feature de contemplação.",
  "Cuidado com o rm -rf: ele não pergunta duas vezes.",
  "Sistema legado é aquele que funciona e ninguém sabe por quê.",
  "O Stack Overflow caiu. A indústria de software inteira tirou o dia de folga.",
  "Meu algoritmo é O(n), onde n é a paciência do usuário.",
  "Ele mexeu num CSS e o botão foi parar na Argentina.",
  "Docker: agora funciona no meu contêiner.",
  "Merge conflict é quando duas boas ideias se odeiam.",
  "Eu faço TDD: Teste Depois, Desculpa.",
  "O bug não é reproduzível, é artesanal.",
  "Adicionei um try/catch. Agora o erro é silencioso e educado.",
  "Backup é aquilo que você descobre que não tem exatamente quando precisa.",
  "Um byte pediu um bit emprestado. Nunca mais se falaram.",
  "Na dúvida, reinicie. Se persistir, reinicie com mais convicção.",
  "A IA vai substituir devs? Ela ainda não sabe o que o cliente quer. Nem o cliente.",
  "Colocamos um índice. O banco agradeceu em silêncio.",
];
